### PR TITLE
fix: Remove donate link from footer; that page was deleted a while ago

### PR DESCRIPTION
**Pull request by timmc-edx**

### CODE REVIEW

**Review by robrap — COMMENTED** [review]
1. Is there versioning for this component?
2. You'll need to update snapshot tests. Not sure if that will fix all the errors around translations.
3. Does any communication need to be done about this change for the Open edX community?

You may get a better review from Frontend WG.

**Comment by timmc-edx** [comment]
No idea on versioning, and I don't think there's any communication needed for Open edX -- this seems to be just edx.org's footer, I think? (There's another repo without the "-edx" in the name.)

For the snapshots, I noticed that when I grepped, but I'm not sure what the correct tool is to update the snapshot. Could do it manually, though. :-)

No idea what's causing the other translation errors.

**Comment by davidjoy** [comment]
1. semantic versioning happens automatically based on the conventional commit prefix when this branch is merged to master.  
2. Snapshot tests can be updated with `npm run test -- -u`
3. No communication to the Open edX community is necessary - this is edX internal.

**Review by davidjoy — CHANGES_REQUESTED** [review]
The translation files for specific languages are updated automatically by the transifex jenkins jobs.  The only one we need to change is the source of them, `src/components/Footer.messages.js` - the changes in the others will be blown away as soon as the job runs anyway.

Otherwise I think this is fine, except for needing to update the snapshots.

**Comment by timmc-edx** [comment]
I'm not set up to run npm, so I updated the snapshot manually. I also backed out the i18n file changes. Same test failures as before.

**Review by davidjoy — APPROVED** [review]

**Comment by davidjoy** [comment]
Looks good to go! 🚢

**Comment by timmc-edx** [comment]
Cool. I guess some of those test failures were spurious, provoked by an earlier, real failure. (-:

**Pull request merged**
